query event_logs($environmentId: String!, $filter: String, $afterLimit: Int) {
  environmentLogs(environmentId: $environmentId, filter: $filter, afterLimit: $afterLimit) {
    timestamp
    message
    severity
  }
}
