query latestDeployments($first: Int! = 4) {
  me {
    workspaces {
      name
      id
      team {
        id
        name
        projects {
          edges {
            node {
              id
              name
              services {
                edges {
                  node {
                    id
                    name
                    deployments(first: $first) {
                      edges {
                        node {
                          id
                          status
                          createdAt
                          updatedAt
                          staticUrl
                          url
                          canRedeploy
                          canRollback
                          projectId
                          serviceId
                          environmentId
                          environment {
                            id
                            name
                          }
                          meta
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
