query projectsServicesEnvironments {
  me {
    workspaces {
      name
      id
      team {
        id
        name
        projects {
          edges {
            node {
              id
              name
              description
              createdAt
              updatedAt
              teamId
              services {
                edges {
                  node {
                    id
                    name
                    createdAt
                    updatedAt
                    projectId
                    icon
                  }
                }
              }
              environments {
                edges {
                  node {
                    id
                    name
                    createdAt
                    updatedAt
                    projectId
                    isEphemeral
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}