query volumeUsage {
  me {
    workspaces {
      id
      name
      projects(first: 100) {
        edges {
          node {
            id
            name
            volumes(first: 100) {
              edges {
                node {
                  id
                  name
                  volumeInstances(first: 100) {
                    edges {
                      node {
                        id
                        currentSizeMB
                        sizeMB
                        mountPath
                        region
                        environment {
                          id
                          name
                        }
                        service {
                          id
                          name
                        }
                      }
                    }
                  }
                }
              }
            }
            environments(first: 100) {
              edges {
                node {
                  id
                  name
                  volumeInstances(first: 100) {
                    edges {
                      node {
                        id
                        currentSizeMB
                        sizeMB
                        mountPath
                        region
                        service {
                          id
                          name
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
