query volume_sizes_simple {
  me {
    workspaces {
      name
      team {
        id
        projects {
          edges {
            node {
              name
              environments {
                edges {
                  node {
                    name
                    volumeInstances {
                      edges {
                        node {
                          currentSizeMB
                          sizeMB
                          mountPath
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
} 